monolog:
    handlers:
        requests:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.request.log"
            level: info
            channels: ["request"]
        security:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.security.log"
            level: debug
            channels: ["security"]
        doctrine:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.doctrine.log"
            level: debug
            channels: ["doctrine"]
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", "!security", "!request", "!doctrine"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
